[book]
title = "Bigdreamer's Kitchen"
authors = ["Bigdreamer"]
language = "zh-cn"
multilingual = false
src = "src"

[output.html]
default-theme = "Light"
mathjax-support = true
git-repository-url = "https://github.com/bigdreamer7/bigdreamer7.github.io"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
